# Generated by Django 6.0.7 on 2026-08-08 17:01

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='telefone',
            field=core.fields.EncryptedCharField(blank=True),
        ),
    ]
