# Generated by Django 6.0.7 on 2026-10-03 10:07

import django.contrib.postgres.fields
import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_utilizador_telefone'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='personaltrainer',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='modalidades_pagamento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('multicaixa', 'Multicaixa Express'), ('dinheiro', 'Dinheiro'), ('transferencia', 'Transferência Bancária')], max_length=20), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='preco_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('instituicao', models.CharField(blank=True, max_length=255)),
                ('ano_obtencao', models.PositiveIntegerField(blank=True, null=True)),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='core.personaltrainer')),
            ],
        ),
        migrations.CreateModel(
            name='SlotDisponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fim', models.TimeField()),
                ('capacidade', models.PositiveIntegerField(default=1)),
                ('vagas_ocupadas', models.PositiveIntegerField(default=0)),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots_disponibilidade', to='core.personaltrainer')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='core.utilizadoraluno')),
                ('personal_trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritado_por', to='core.personaltrainer')),
            ],
            options={
                'unique_together': {('aluno', 'personal_trainer')},
            },
        ),
    ]
