# Generated by Django 6.0.7 on 2026-10-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pt_marketplace_modelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='localizacao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
