# Generated by Django 6.0.7 on 2026-10-03 10:32

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pt_localizacao'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='personaltrainer',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='pt_embedding_hnsw', opclasses=['vector_cosine_ops']),
        ),
    ]
