# Generated by Django 6.0.7 on 2026-10-03 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pt_embedding_hnsw'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='janela_cancelamento_horas',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='sessao',
            name='cancelada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessao',
            name='data_cancelamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='modalidade',
            field=models.CharField(choices=[('individual', 'Individual'), ('pacote', 'Pacote'), ('plano_mensal', 'Plano Mensal')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='sessao',
            name='quantidade_sessoes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sessao',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessoes', to='core.slotdisponibilidade'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='estado',
            field=models.CharField(choices=[('agendada', 'Agendada'), ('confirmada', 'Confirmada'), ('em_curso', 'Em Curso'), ('realizada', 'Realizada'), ('avaliada', 'Avaliada'), ('cancelada', 'Cancelada')], default='agendada', max_length=20),
        ),
    ]
