# Generated by Django 6.0.7 on 2026-10-03 10:51

from django.db import migrations, models


def converter_estados_antigos(apps, schema_editor):
    Pagamento = apps.get_model("core", "Pagamento")
    Pagamento.objects.filter(estado="concluido").update(estado="aprovado")
    Pagamento.objects.filter(estado="falhado").update(estado="recusado")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sessao_maquina_de_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='comissao_plataforma',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_aprovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data_libertacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor_liquido_pt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='estado',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('libertado', 'Libertado'), ('reembolsado', 'Reembolsado')], default='pendente', max_length=20),
        ),
        migrations.RunPython(converter_estados_antigos, migrations.RunPython.noop),
    ]
