# Generated by Django 6.0.7 on 2026-10-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pagamento_maquina_de_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='data_realizacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessao',
            name='reclamacao',
            field=models.TextField(blank=True),
        ),
    ]
