# Generated by Django 6.0.7 on 2026-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_sessao_realizacao_reclamacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='lembrete_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
