# Generated by Django 6.0.7 on 2026-10-03 12:14

from django.db import migrations, models


def calcular_reputacao_existente(apps, schema_editor):
    from django.db.models import Avg, Count
    PersonalTrainer = apps.get_model("core", "PersonalTrainer")
    Avaliacao = apps.get_model("core", "Avaliacao")
    for pt in PersonalTrainer.objects.all():
        agg = Avaliacao.objects.filter(
            avaliado_id=pt.utilizador_id, sessao__estado__in=["realizada", "avaliada"]
        ).aggregate(media=Avg("classificacao"), total=Count("id"))
        if agg["total"]:
            pt.classificacao_media = round(agg["media"], 2)
            pt.total_avaliacoes = agg["total"]
            pt.save(update_fields=["classificacao_media", "total_avaliacoes"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_avaliacao_mutua'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='classificacao_media',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='personaltrainer',
            name='total_avaliacoes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(calcular_reputacao_existente, migrations.RunPython.noop),
    ]
