# Generated by Django 6.0.7 on 2026-10-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pt_reputacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrainer',
            name='avaliacoes_desde',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personaltrainer',
            name='estado_verificacao',
            field=models.CharField(choices=[('pendente', 'Pendente de Verificação'), ('verificado', 'Verificado'), ('em_alerta', 'Em Alerta'), ('suspenso', 'Suspenso')], default='pendente', max_length=20),
        ),
    ]
