# Generated by Django 6.0.7 on 2026-10-03 12:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pt_estados_qualidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ginasio',
            name='equipamentos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ginasio',
            name='estado_parceria',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parceiro', 'Parceiro'), ('inativo', 'Inativo')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='ginasio',
            name='horarios',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ginasio',
            name='personal_trainers',
            field=models.ManyToManyField(blank=True, related_name='ginasios', to='core.personaltrainer'),
        ),
    ]
