# Generated by Django 6.0.7 on 2026-10-03 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_ginasio_parceria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaGinasio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aula_experimental', 'Aula Experimental'), ('visita', 'Visita')], max_length=20)),
                ('data_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_ginasio', to='core.utilizadoraluno')),
                ('ginasio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.ginasio')),
                ('personal_trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_ginasio', to='core.personaltrainer')),
            ],
        ),
    ]
