# Generated by Django 6.0.7 on 2026-10-03 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_reserva_ginasio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilizador',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('personal_trainer', 'Personal Trainer'), ('nutricionista', 'Nutricionista')], max_length=20),
        ),
        migrations.CreateModel(
            name='Nutricionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_verificacao', models.CharField(choices=[('pendente', 'Pendente de Verificação'), ('verificado', 'Verificado')], default='pendente', max_length=20)),
                ('cedula_profissional', models.CharField(blank=True, max_length=100)),
                ('especialidade', models.CharField(blank=True, max_length=255)),
                ('biografia', models.TextField(blank=True)),
                ('utilizador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_nutricionista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
