# Generated by Django 6.0.7 on 2026-10-03 19:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_nutricionista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planonutricional',
            name='personal_trainer',
        ),
        migrations.AddField(
            model_name='planonutricional',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planonutricional',
            name='calorias_diarias',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planonutricional',
            name='nutricionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planos', to='core.nutricionista'),
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(6)])),
                ('hora', models.TimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('calorias', models.PositiveIntegerField(default=0)),
                ('proteinas_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('carboidratos_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('gorduras_g', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='core.planonutricional')),
            ],
        ),
        migrations.CreateModel(
            name='RegistoRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('calorias', models.PositiveIntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registos_refeicao', to='core.utilizadoraluno')),
                ('refeicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registos', to='core.refeicao')),
            ],
        ),
    ]
