# Generated by Django 6.0.7 on 2026-10-03 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_plano_nutricional_refeicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('suplemento', 'Suplemento'), ('vestuario', 'Vestuário')], default='suplemento', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
