# Generated by Django 6.0.7 on 2026-10-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_carrinho_encomenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoEncomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente_pagamento', 'Pendente de Pagamento'), ('paga', 'Paga'), ('em_preparacao', 'Em Preparação'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('cancelada', 'Cancelada')], max_length=20)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('encomenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.encomenda')),
            ],
            options={
                'ordering': ['data', 'id'],
            },
        ),
    ]
