# Generated by Django 6.0.7 on 2026-10-03 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_evento_encomenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenciaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('ano', models.PositiveIntegerField()),
                ('ultimo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tipo', 'ano'), name='sequencia_unica_por_tipo_e_ano')],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FT', 'Fatura'), ('RC', 'Recibo')], max_length=2)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('linhas', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_financeiros', to=settings.AUTH_USER_MODEL)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='core.pagamento')),
            ],
            options={
                'ordering': ['-data_emissao', '-id'],
                'constraints': [models.UniqueConstraint(fields=('pagamento', 'tipo'), name='um_documento_por_tipo_e_pagamento')],
            },
        ),
    ]
