# Generated by Django 6.0.7 on 2026-10-03 19:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_faturacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParceriaPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('ativa', 'Ativa'), ('recusada', 'Recusada'), ('terminada', 'Terminada')], default='pendente', max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('remuneracao_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('personal_trainer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parceria', to='core.personaltrainer')),
            ],
        ),
        migrations.CreateModel(
            name='RemuneracaoParceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('parceria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remuneracoes', to='core.parceriapt')),
            ],
            options={
                'ordering': ['-mes'],
                'constraints': [models.UniqueConstraint(fields=('parceria', 'mes'), name='uma_remuneracao_por_mes')],
            },
        ),
    ]
